SUI-Components/sui-theme

- README.md
- src/_functions.scss
- src/_mixins.scss
- src/_settings.scss
- src/components/_button.scss
- src/components/_input.scss
- src/components/_select.scss
- src/components/_tabs.scss
- src/index.scss
- src/layout/_grid.scss
Incrementamos funcionalidad del theme basics para poder construir componentes con estilos básicos definidos por el equipo de UX.
https://zpl.io/Z1vTaF5
Se han añadido utilidades tipo variables, helpers, placeholders, functions y mixins.
> Feature: New UI Components styles and settings

- src/_settings.scss
- src/components/_input.scss
- src/components/_select.scss
> Fixed some issues.

- src/_settings.scss
- src/components/_tabs.scss
> add tab styles

- src/_settings.scss
- src/components/_button.scss
- src/components/_card.scss
- src/layout/_grid.scss
> Added new button types. Some fixes.

- src/_settings.scss
> Fixed some font sizes. Added new spacing sizes.

- src/components/_button.scss
> Fixed font size for button large.

- src/_settings.scss
> add social colors

- src/_reset.scss
- src/layout/_grid.scss
@SUI-Components/developers 
* Added a reset mixin for lists (ul, ol).
* Improved grid cell in order to make them adapt to a specific number of colums through the mixin: `sui-cell-of($columns-number)`.
> Improved grid system

- src/components/_button.scss
- src/layout/_grid.scss
@SUI-Components/developers please review! It's just what the title says.
Example of the new vertical gutter added to grid cells:
> Fixed large button size. Added vertical margin to grid cells.

- src/_reset.scss
- src/icons/_arrow.scss
- src/index.scss
> Added reset button and icon arrow in CSS.

- src/_settings.scss
Adding variables to setup dropdown styles
> add dropdown styles

- src/_reset.scss
- src/_settings.scss
- src/utils.scss
- src/utils/_text.scss
@SUI-Components/developers please review
> Added utils for texts. Fixed some vars.

- src/_settings.scss
- src/components/_button.scss
* Added default vars for new SUI Component: __Topbar User__.
* Improved button mixin:
* Now it's possible to customize the basic button by setting a custom background color: `sui-button($color: '#cccccc')`
* If you wrap an icon (e.g.: `.sui-MyComponent-buttonIcon`) within a button (`sui-button`), icon now it's properly aligned and colored regarding the button text.
@SUI-Components/developers please review.
> Added default vars for topbar user. Improved button mixin.

- src/_reset.scss
> Fixed font family for buttons.

- src/_settings.scss
Adding ads component variables
> add ads variables

- src/_settings.scss
set nav width to 90% instead of 75%
> fix topbar nav width

- src/layout/_grid.scss
two new features: 
- add gutter as a parameter
- add inline-grid
> enhance grid system

- src/_settings.scss
Add radio list component vars to theme basic
> add radio list vars

- src/_reset.scss
- src/_settings.scss
- src/utils.scss
- src/utils/_image.scss
@SUI-Components/developers please review.
> Added card product settings. Added aspect ratio mixin. Improved button reset.

- src/_settings.scss
@SUI-Components/developers 
New variable based on definition by UX https://zpl.io/18FDdJ
> Added warning variable.

- src/_settings.scss
> add featured card variables

- package.json
- src/components/_button.scss
please review @SUI-Components/developers
> adds default value

- src/components/_button.scss
This is a major version change.
> Add button type custom.

- src/_settings.scss
- src/components/_button.scss
> Adapt button colors regarding Components UI definition.

- src/components/_button.scss
> Reset default button border in sui-button mixin.

- src/_settings.scss
> add min height to add l top

- src/_settings.scss
add autocompleted button type var
> add autocompleted button type var

- src/_settings.scss
adjusting form autocompleted in order to center clear button vertically
> adjust form autocompleted

- src/_settings.scss
related to https://github.com/SUI-Components/sui-components/pull/101
> add breadcrumbs vars

- src/_settings.scss
adding `background color` and `box shadow` properties in order to fit with motor design requeriments.
> adjust breadcrumb params

- src/_settings.scss
removing padding from `mt-component` in order to manage it from the `sui-component`.
> adjust breadcrumb paddings

- src/_settings.scss
Add two new variables for the new component and fix the size of the font.
> Add variables for icon button on cookie banner

- src/_settings.scss
Add default sass variables for title-basic and title-multisize components.
> (feature/title-vars):add new title variables (basic, multisize)

- src/_settings.scss
- src/utils.scss
- src/utils/_list.scss
I've created a new mixin for lists. I've contemplated 3 possibilities:  list elements in vertical (as default), list elements inline and a list inline where the items grow and distributed equally
Example for this mixin: https://codepen.io/anon/pen/VzKZXO
> new list mixin

- src/components/_button.scss
- Fix `icon`classname following SUIT naming convention
- Fix button medium icon size, following SUI UX definition (icon size should be small in medium buttons)
**This is a breaking change, so i will upgrade a Major version**
> fix icon selector, modify button icon medium

- src/_settings.scss
Add needed variables for Sui-CardComposable.
> Add variables needed for sui-card-composable

- src/_settings.scss
- src/settings-compat-v7/_spacing.scss
- src/settings/_spacing.scss
Refactor os spacings.
No p-v or p-h where added as it's no a concept of design.
But, later on we could talk about creating these variables in the "new" settings
> refactor(settings): set spacing varaibles from new design

- src/_settings.scss
- src/settings-compat-v7/_font.scss
- src/settings/_font.scss
Many compatibility variables were preserved.
> refactor(settings): create font variables from new design

- CHANGELOG.md
- package.json
- src/settings/_color.scss
Fix for the "$c-price error" (already published)
> Fix func colors

- src/settings/_color.scss
@SUI-Components/developers please review.
> fix(settings): apply color changes from design

- src/components/_settings.scss
These variables will be used by the following components:
sui-form-text-input
sui-form-checkbox
sui-form-textarea
> feat(components): add new vars for form elements: input, textarea, checkbox.

- README.md
- src/index.scss
- src/settings-compat-v7/_index.scss
This with help us for refactoring is uilib-components repos, adding a simple line for v7 compatiblity
https://github.com/SUI-Components/sui-theme/pull/107/files#diff-04c6e90faac2675aa89e2176d2eec7d8R48
> Add an easier way to make fully compatible with v7

- src/settings/_color.scss
Can be checked here https://app.zeplin.io/project/57c02a80c1caf50b0d2e851e/screen/598af71c138655ba087ce28c
> fix(settings): new success, alert and error colors

- src/components/_badge.scss
- src/index.scss
- src/settings-compat-v7/_components.scss
Add badge notifications in dropdown component.
> add scss variables for bagde notifications

- src/layout/_grid.scss
- src/settings-compat-v7/_spacing.scss
- Modify grid system in order to be able to use custom gutters.
- Add `$gutter-s` to be used in grids with a small gutter.
> add custom gutter to grid

- src/settings-compat-v7/_components.scss
adding  a z-index var, in order to overwrite it in mt-theme.
> add z-index var

- src/settings-compat-v7/_components.scss
These vars have been moved to their corresponding components, refactored to adapt them to sui-theme@8 in PR https://github.com/SUI-Components/sui-components/pull/193
> feat(settings-compat-v7): remove title and cover vars from settings-compat-v7 file.

- src/settings-compat-v7/_components.scss
And moved to sui-component repo, to their corresponding component) in PR https://github.com/SUI-Components/sui-components/pull/196
> feat(settings-compat-v7): remove form elements vars from settings-compat7-file

- src/settings-compat-v7/_components.scss
defined in component stylesheet
https://github.com/SUI-Components/sui-components/pull/226
> remove collapsible vars

- src/settings-compat-v7/_components.scss
removing variables and exporting to component topbar user
> feat(settings-compat-v7): remove variables and export to component 

- src/settings-compat-v7/_animation.scss
> add transition fast

- src/settings-compat-v7/_components.scss
These vars has been moved to the sui-list-image component in PR https://github.com/SUI-Components/sui-components/pull/269
> feat(settings-compat-v7): remove vars for list image component.

- src/settings/_color.scss
> feat(settings): add instagram color

- src/utils/_forms.scss
I've created a new mixin for forms elements: inputs, textareas and their own sizes, validations (success or alert) and help text
> mixin for form elements

- src/settings/_box-style.scss
Added variable for the need of the `Tooltip` component
There's still a pending review of these `bdrs` variables and values that will be done in another task in sync with the UI department
> feat(settings): added bdrs-l variable

- src/components/_card.scss
Also remove not needed `sui-card--small` modifier, because it duplicates styles from its parent mixin `sui-card`.
> feat(components): add card title primary style

- src/settings/_box-style.scss
Added new variables for `box-shadow` defined in specification → https://paper.dropbox.com/doc/SUI-Basic-Styles-0ko2wfsTt1JOQHV6G8cwo
> feat(settings): added box-shadow variables according basic styles specifications

- src/utils/_colors.scss
Taking out the color steps of the method we can configure them in each vertical.
> feat(utils): add configurable color steps

- src/components/_card.scss
This is related to this PR https://github.com/SUI-Components/sui-components/pull/496
Add the possibility to have a `CTA` in the `BasicCard`
> feat(components): add styles for action section in BasicCard

- src/settings/_color.scss
https://github.com/SUI-Components/sui-components/pull/531#discussion_r219430190
> feat(settings): add variable for highlight color

- src/settings/_box-style.scss
- ⚙️ Task → https://jira.scmspain.com/browse/SUIC-14
- 🗓 Specification → https://paper.dropbox.com/doc/SUI-Border-radius--AVy3HnWiRpbPA7neDmWaN6IBAg-r25h121XDdOaOTccye7Xo
> feat(settings): border radius tokens

- src/_typography.scss
- ⚙️ Task → https://jira.scmspain.com/browse/SUIC-101
- 🗓 Specification → https://paper.dropbox.com/doc/SUI-Font--AVMpxYUtK5pxu6ycRYFhoq_yAg-qpkHuaM6HWxCJP0Mm6EpL
> feat(META): links typography

- src/settings-compat-v7/_components.scss
Defining dropdown vars so we can overwrite them from our themes.
Related PR: https://github.schibsted.io/scmspain/frontend-mt--uilib-theme/pull/111
> define dropdown vars

- src/components/atom/input/_placeholders.scss
- src/components/atom/input/_settings.scss
I've added a new placeholder to set different values for border and box-shadow to autosuggest and input
> feat(components): add new placeholder for autosuggest when is focused

- src/components/atom/input/_settings.scss
A third state added, orange for `alert`.
> feat(components): add alert state for atom input sui component

- package-lock.json
- package.json
- src/settings/_motion.scss
We need a Motion guideline, to define the baseline to transitions and animations in SUI Components.
We start with settings the variables to define the **durations** and the **timing functions** tokens.
I propose a verbose naming and when define aliases
```
.element {
...
transition: transform $duration-slow $timing-function-ease-out,
background-color $duration-slow,
box-shadow $duration-slow $duration-fast;
...
}
```
> feat(settings): added Motion variables settings

- src/utils/_colors.scss
From ePreselec we need to customize our variation with the color black.
> fix(utils): add customizable black and white in mixin function

- src/_settings.scss
import settings/motion in settings file
> fix(Root): import settings motion

- src/utils/_colors.scss
we need to move this var out of scope to redefine our black, by default we don't use pure black in our theme.
> feat(utils): define var as global var

- src/settings/_spacing.scss
we need a gutter with 32px of size
> feat(settings): add large size for gutter

- src/settings/_box-style.scss
Create new `bdrs-xxl` in order to use it on Molecule component and Fotocasa Pro component.
> feat(settings): create bdrs xxl variable

- README.md
> docs(Root): improve and fix README documentation

- src/utils/_grid.scss
Fixed expanded columns when the content is bigger.
View component PR here: https://github.com/SUI-Components/sui-components/pull/1369
> feat(utils): update flex bassis to min-width property

- .gitignore
- package.json
- src/settings/_box-style.scss
JIRA TICKET: https://jira.scmspain.com/browse/SUIC-206
ISSUE: https://github.com/SUI-Components/sui-components/issues/1273
Add the border radius variable needed
> feat(settings): add border radius variables

- src/utils/_grid.scss
> feat(utils): add grid parent mixin

- src/components/_badge.scss
- src/components/_select.scss
- src/settings-compat-v7/_box-style.scss
- src/settings-compat-v7/_components.scss
- src/settings/_box-style.scss
- src/utils/_forms.scss
> feat(Root): normalize border variables

- src/components/atom/input/index.scss
All sui-theme resolver import methods use the same relative path
> refactor(components): unify import resolver methods
