- src/components/_card.scss
Adjusting `padding` and title `font-size`, in order to fit with `news detail` design
> Card article: adjust padding and title font-size

- src/_settings.scss
- src/components/_button.scss
- src/components/_input.scss
- src/components/_select.scss
- Add customizable `line-height` to button, so large buttons increases its height.
- Set `inputs` and `selects` sizes, by passing the parameter `medium` or `large`  to the mixin (default is `medium`).
- switch `border` to `box-shadow` in `selects` and `inputs`, so they can be aligned with buttons.
**CAUTION:**
if you are overwriting some of this variables in your theme:
`$bd-input`
`$bd-input-hover`
`$bd-input-hover`
`$bd-select`
`$bd-select-hover`
`$bd-select-focus`
you may want to change your border declarations to box shadow. 
ie: `$bd-select: 1px solid $your-color` -> `$bd-select: 0 0 0 1px $your-color inset`
> form elements refactor

- src/components/_button.scss
fixing icon button selector following SUIT naming convention
this PR is related to https://github.schibsted.io/scmspain/frontend-mt--uilib-components/pull/166
> fix icon button selector

- src/_settings.scss
- src/utils/_breakpoints.scss
Moved sui-section-basic variables to theme-basic.
Additionally, an error in breakpoints mixins has been solved, removing a unnecesary variable which was generating the following error when using "media-breakpoint-between" and "media-breakpoint-only" mixins:
**Module build failed: 
@include media-breakpoint-between($name, $name, $breakpoints) {
^
Wrong number of arguments (3 for 2) for `media-breakpoint-between'
in node_modules/@schibstedspain/theme-basic/lib/utils/_breakpoints.scss (line 75, column 12)
Error: 
@include media-breakpoint-between($name, $name, $breakpoints) {
^
Wrong number of arguments (3 for 2) for `media-breakpoint-between'**
> feat(components): add new variables for component section basic.

- src/_settings.scss
- src/settings-compat-v7/_color.scss
- src/settings/_color.scss
- src/utils/_colors.scss
For now, the compatibility layer is added to the main settings during the refactor to check everything works fine as a whole.
When refactor ends we'll remove compa imports and bump to major version (@s-ui-theme)
Color where changed. They may vary but it should not affect projects.
> refactor(settings): refactor colors to be compliant to new design

- README.md
- package.json
- src/_settings.scss
New version of the theme only with "official" variables from new design.
This repo was rename to sui-theme and the NPM package renamed to schibstedspain/sui-theme
> Sui theme v8

- src/index.scss
- src/settings-compat-v7/_font.scss
- src/utils.scss
- src/utils/_numbers.scss
This definition used in `src/settings-compat-v7/_font.scss` worked fine in V7:
```scss
$fz-base: 14
$fz-body: $fz-base * 1px !default; // 14px
```
but, since V8 has units, the compiler breaks trying to calculate the operation:
```scss
$fz-base: 14px
$fz-body: $fz-base * 1px !default; // ERROR:  14px*px isn't a valid CSS value.
```
To solve this, we decided to add a `strip-unit` function in order to be able to define `$fz-base` with or without units:
```scss
$fz-base: 14px
$fz-body: strip-unit($fz-base) * 1px !default; // 14px
```
```scss
$fz-base: 14
$fz-body: strip-unit($fz-base) * 1px !default; // 14px
```
otherwise we can't define font sizes with units (as in sui-theme V8) in mt-theme.
> add strip unit to compat font

- src/components/_badge.scss
- src/components/_button.scss
- src/components/_card.scss
- src/components/_input.scss
- src/components/_tabs.scss
- src/components/_tag.scss
- src/settings-compat-v7/_index.scss
- src/settings/_color.scss
- src/settings/_spacing.scss
A couple of changes from the meeting: https://confluence.schibsted.io/display/ST/2017-10-17+Meeting+%7C+sui-theme+and+sui-components?focusedTaskId=3
Also, I've refactored a litlle bit to reduce linter's warnings and avoid comments to be transpiled (even if we remove them by post-css in the builds)
> Changes from meeting

- src/settings-compat-v7/_spacing.scss
- src/settings/_spacing.scss
- Adding spacing compat values as a comment.  The reason for that is easily identify values when updating to new naming variables.
- fix linting errors in spacing operators
> add spacing comented values

- src/utils/_list.scss
I've changed the gutter approach for `inline` and `grow` lists types.
Why?
Until now, we have a gutter as a `margin-right` for all items of the list **except the last one**. That made that the last item of the list had a bigger height in IE. I've fixed it changing `margin-right` for `margin-left` **for all elements** and put that gutter value as negative margin for the list.
> fix height items for grow lists on ie

- src/components/_button.scss
- src/components/_input.scss
- src/components/_select.scss
Please, review. Instead of overwriting the font-family, we just use inherit in order to keep consistency with the overall website. So, this will not fire the load of the font-face yet if not needed.
> Inherit font family for some elements instead overwriting

- src/settings-compat-v7/_components.scss
Adding `$c-dropdown-button-large` and `$c-dropdown-user-text-large` in order to be able to define a motos black topbar.
NOTE: i'm not migrating all variables because there are shared variables between components.
> add dropdown vars

- src/index.scss
Refactor was done to make all components compatible with the change:
* https://github.com/SUI-Components/sui-components/pull/327
* https://github.schibsted.io/scmspain/frontend-fc--uilib-components/pull/196
* https://github.schibsted.io/scmspain/frontend-mt--uilib-components/pull/278
The plan is to merge first the above PRs, and afterwards publish this new version of sui-theme.
We can do a new major of sui-theme but it doesn't make really sense as sui-theme is loaded by centralized [sui-component-dependencies](https://github.com/SUI-Components/sui/blob/master/packages/sui-component-dependencies/package.json#L13)
No need to refactor NC or CF because they already add `@import '~@schibstedspain/sui-theme/lib/settings';` to have the new variables.
> feat(META): remove compat variables by default

- src/layout/_breakpoints.scss
[Definition](https://paper.dropbox.com/doc/SUI-Basic-Styles-0ko2wfsTt1JOQHV6G8cwo) @ breakpoints section
Added `zero` in order to be fully able to use the [breakpoints utils](https://github.com/SUI-Components/sui-theme/blob/master/src/utils/_breakpoints.scss). 
**Need help: Do you think UX should add `zero`  into the definition?**
> feat(layout): sui breakpoints

- src/components/atom/input/_placeholders.scss
- src/components/atom/input/_settings.scss
- src/components/atom/input/index.scss
- src/index.scss
In order to be able to share these styles with other componentes (`MoleculeInputTags`, `MoleculeSelect`,...) these styles should be moved to `sui-theme`
> feat(components): shared styles from atomInput

- src/components/atom/input/_placeholders.scss
Better common placeholder for "input" components (`AtomInput`, `MoleculeInputTags`, `MoleculeSelect`) by setting a `min-height` instead of a `height`
> feat(components): min-height placeholder atom-input

- src/settings/_color.scss
Add colors gradient sass variables to have more customizable colors in the projects that are using sui-theme. It would make communication between UX/Devs easier standardizing and linking Zeplin designs with our sass color variables. It follows the following color gradation scheme:
> feat(settings): add colors gradient sass variables

- package.json
- src/components/atom/input/_settings.scss
We need to add an smaller size sass var to `atom-input` component.
Is backwards compatible with current implementation.
Avoids a bug in Firefox Browser when using with label:
> Adds xs size to AtomInput

- src/components/atom/input/_settings.scss
adds a missing `xs` size for AtomInput
> feat(components): adds a missing xs size in atom input

- src/components/atom/input/_placeholders.scss
The `min-height` value in `%sui-atom-input-input` class was overriding other modificator class values like `.sui-AtomInput-input-m`,
`.sui-AtomInput-input-s` and `.sui-AtomInput-input-xs` to apply.
Now, values defined by `$h-atom-input--m`, `$h-atom-input--s` or `$h-atom-input--xs` are just working ok:
**After fix:**
`min-height` value is determined by its size modificator class:
**Before fix**
Harcoded value was always applied:
Please review
> fix(components): removes hardcoded value

- src/utils/_list.scss
I've fixed flex direction and I've added a new list case:
for default, `grow` list is `flex: 1 1 100%;` but with `grow-custom` we can add a custom flex grow (p.e)
> fix(utils): fix flex direction

- src/settings/_box-style.scss
In order to handle property values in a more declarative way, this PR adds a base value for **BorderRadius** property so we'll be able to define bigger o smaller values as stated [in this other PR](https://github.com/SUI-Components/sui-components/pull/814).
To do so, older values previously declared must be deprecated.
Please review
> feat(settings): adds $bdrs-base sass var to standarize border-radius

- src/settings/_size.scss
This new size variable would be useful for some use cases such as the AtomActionButton which requires 48px for its large size, 40px for its medium / default size and 32px for its small size.
> feat(settings): add new size variable $sz-icon-xxl

- src/settings/_color.scss
This PR adds a new **sui-color** named `$c-secondary` and by default will have same color of `$c-accent`.
This option will allow other verticals to use in their defined secondary color in sui-components instead of overriding the component. 
So now, if we adapt our 'sui-components' to use this new color, we could use it like this: 
```javascript 
<AtomTooltip color="secondary" />
```
> feat(settings): add new secondary color

- src/_settings.scss
#217 introduced an error by ordering settings imports → `box-style` consumes `$c-primary` and cannot be placed before `colors` import.
> fix(Root): import settings order for var consuming

- src/utils/_grid.scss
Adjust spacing with parent container to fit correctly.
> feat(utils): prevent gap with parent container

- src/settings/_box-style.scss
Version `8.92.0` introduces a bug at components depending on the `bdrs-none` variable, p.ex. the `atom/table`
```
SassError: Undefined variable: "$bdrs-none".
on line 6 of components/campaign/list/node_modules/@s-ui/react-atom-table/lib/index.scss
```
This PR restores the removed variable to fix the error.
> fix(settings): fix components using bdrs-none
